-- ユーザーテーブル
CREATE TABLE IF NOT EXISTS users (
  id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name VARCHAR(16) NOT NULL,
  email TEXT UNIQUE NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP(0)
);

-- リストテーブル

-- カードテーブル
CREATE TABLE IF NOT EXISTS cards (
  id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  title VARCHAR(16) NOT NULL,
  description TEXT,
  position INTEGER NOT NULL,
  completed BOOLEAN DEFAULT false,
  dueDate DATE,
  list_id INTEGER REFERENCES lists(id) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP(0)
);